name: deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js 16.13.2
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.2

      - name: Setup npm 8.1.2
        run: npm i -g npm@8.1.2

      - name: Install dependencies
        run: npm ci

      - name: Deploy application
        run: npx gatsby@4.6.0 build --prefix-paths && npx gh-pages@3.2.3 -d public -r https://${{ secrets.GH_TOKEN }}@github.com/ricardani/medicina-integrativa.git
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}