name: deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js 16.13.2
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.2

      - name: Setup npm 8.1.2
        run: npm i -g npm@8.1.2

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Deploy application
        run: ./scripts/deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          DEPLOY_TOKEN: ${{ secrets.GH_TOKEN }}